#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <getopt.h>
#include <stdarg.h>
#include <stdlib.h>
#include <iostream>
#include <cstdlib>
#include <fstream>
#include <vector>
#include <math.h>
#include "colors.h"
#include "isa.h"
#include "copy.h"
#include "rapidxml.hpp"
#include "rapidxml_print.hpp"
